### ISSUE TITLE
starting or stopping service

### ISSUE THREAD

**Issue by Jaimy85** [gekmihesg/ansible-openwrt#39]
I'm trying to start or stop a service, but the is_running function is not working for me.
"/etc/init.d/uhttpd running" is always returning 0.
It seems that rc.common is always returning 0 for is_running in OpenWrt 19.07, from 21.02 there is a change but now it is always returning 1.
I can add the "pattern: uhttpd" in playbook, this is working.
Maybe because "running" had to be implemented per init.d script?
Do I have to add the pattern option to every service in the playbook?

**Comment by AiyionPrime** [comment]
I'm currently running OpenWrt 21.02 and can not confirm the issue yet.

May you share an example of what playbook is not working?
At least in OpenWrt 21.02 the init.d script does return its status as intended.

```console
root@netgear_gs108tv3:~# /etc/init.d/uhttpd status
running
root@netgear_gs108tv3:~# /etc/init.d/uhttpd running; echo $?
0
root@netgear_gs108tv3:~# /etc/init.d/uhttpd stop; echo $?
0
root@netgear_gs108tv3:~# /etc/init.d/uhttpd running; echo $?
1
root@netgear_gs108tv3:~# /etc/init.d/uhttpd start; echo $?
0
```

**Comment by gekmihesg** [comment]
Sadly, this has always always been implemented very inconsistently in OpenWRT. I can confirm that for `uhttpd` on 19.07 this did always return 0 but for 21.02.1 this should be working correctly. I didn't really look into this in detail, but as far as I remember, this is some functionality that should have been provided by `procd` but was partially broken. Some services implemented that on their own instead, which is why it was working for some exceptions.
Anyway, if it doesn't work out of the box, then yes, you have to use pattern, no way around it.
